---

INSTALL_PATH: "/opt/magicstackfalcon-agent"

enable_agent: true

agent:
  plugin_enable: "true"

  http_eanbled: "false"
  http_listen: 1988

  transfer: "10.1.121.161"
  transfer_port: 8433

  heartbeat_addr: "10.1.121.161"
  heartbeat_addr_port: 8200

  collector_net:
    - "eth"
    - "em"
    - "enp"
    - "eno"
